### ISSUE TITLE
%tensorflow_version 2.x load TF 2.1-rc1 by design or bug?

### ISSUE THREAD

**Issue by JerryKurata** [googlecolab/backend-container#17]
I have been using %tensorflow_version 2.x in all my notebooks to ensure I get the latest version.  So far it was been loading 2.0.  Today it switched to loading 2.1.0-rc1 and my code broke because of a bug in 2.1.0-rc1.  Is this switching to the latest RC by design?

If so, how can we load the latest released version of TensorFlow (i.e. not an RC) without hardcoding it in a pip install command?

Just for completeness the bug is in 2.1.0-rc1 is 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'append'"

**Comment by craigcitro** [comment]
In general, we try to follow TF releases closely. If you hit a bug, I'd recommend filing upstream if it's not already reported. If you want to guarantee a particular version of any dep, especially TF, I'd recommend a `!pip install pkg==ver` at the top of your notebook.

**Comment by JerryKurata** [comment]
No problem.  Switched back to install with pip and ver. 

However, it might we worth considering whether to install RCs with %tensorflow_version, since by their very nature RC are not final release versions.
