### ISSUE TITLE
Allow Viewing of plaintext files in the same way you can view python files

### ISSUE THREAD

**Issue by Kreijstal** [googlecolab/backend-container#19]
I was playing with google colab, and I checked that you could open python files because I hovered over a toolbox, where it says "view source" there was a href link with a URLEncoded that reads something like this 
`<a href="#" data-href="command:viewSource?%5B%22%2Fusr%2Flocal%2Flib%2Fpython3.6%2Fdist-packages%2Ftensorflow%2Fpython%2Feager%2Fwrap_function.py%22%2C%7B%22startLineNumber%22%3A232%2C%22startColumn%22%3A1%2C%22endLineNumber%22%3A232%2C%22endColumn%22%3A1%7D%5D" title="command:viewSource?%5B%22%2Fusr%2Flocal%2Flib%2Fpython3.6%2Fdist-packages%2Ftensorflow%2Fpython%2Feager%2Fwrap_function.py%22%2C%7B%22startLineNumber%22%3A232%2C%22startColumn%22%3A1%2C%22endLineNumber%22%3A232%2C%22endColumn%22%3A1%7D%5D">View source</a>`

Couldn't you use the same technique to preview plain textfiles?

**Comment by craigcitro** [comment]
Could I ask you to re-file this over on https://github.com/googlecolab/colabtools?

**Comment by Kreijstal** [comment]
ok https://github.com/googlecolab/colabtools/issues/1352
