### ISSUE TITLE
Tensorboard on Colab

### ISSUE THREAD

**Issue by ricardobarroslourenco** [googlecolab/backend-container#4]
I'm a recent user of colab, and using tensorflow. I would like to know if it is possible to run tensorboard on a colab notebook. When running locally, or on another VM is easy to tunnel tensorboard, but on colab seems difficult.

**Comment by MerceaOtniel** [comment]
Hello! I have managed to put together multiple commands to create a template for accessing Tensorboard in Google Colaboratory. I did this for Keras. Here is the link 

https://github.com/MerceaOtniel/Google-Colaboratory-Tensorboard-Setup

**Comment by HyunSeok-Kim** [comment]
Hello, I'd like to know how to use colab tensorboard without Keras. 
Thanks in advance.

**Comment by ricardobarroslourenco** [comment]
Hey @colaboratory-team , is there any planning on giving _official_ support to tensorboard ?

**Comment by colaboratory-team** [comment]
The TensorBoard team has released a `%tensorboard` magic now available for Colab. A demo notebook is available here:

https://colab.research.google.com/github/tensorflow/examples/blob/master/community/en/tensorboard/tf_dev_summit_2019.ipynb
